version: '3.2'
services:
  domens:
    build:
      dockerfile: Dockerfile
    ports:
      - 3500:3500
    volumes:
      - /Users/evgeniybye/tasks/domens-scan-service/config:/config
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: Security
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - /Users/evgeniybye/Desktop/db:/var/lib/mysql
  rabbitmq:
    container_name: localhost_rabbitmq
    image: rabbitmq:3.10.7-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672   


